WorkSpyder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exploreFairs.urls')),
    path('management/', include('fairManagement.urls')),
    path('attendance/', include('fairAttendance.urls')),
    path('post/', include('fairsPost.urls')),
    path('auth/', include('auth.urls')),
    path('profile/', include('userProfile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth/urls.py
from django.urls import path
from . import views
#Agregado pata el login
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='view_fairs'), name='logout'),
   ]

exploreFairs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import view_fairs, fair_detail_view

urlpatterns = [
    path('', view_fairs, name='view_fairs'),
    path('fair/<int:id>/', fair_detail_view, name='fair'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fairManagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import register_fair, error_inscripcion, favorite_fair

app_name = 'management'

urlpatterns = [
    path('<int:fair_id_>', register_fair, name='register_fair'),
    path('error-inscripcion/<str:message>/', error_inscripcion, name='error_inscripcion'),
    path('favorite-fair', favorite_fair, name='favorite_fair'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exploreFairs/models.py
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from django.core.exceptions import ValidationError
from fairManagement.models import FairRegistration

class JobFair(models.Model):
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='job_fairs', null=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    start_event_date = models.DateField()
    end_event_date = models.DateField(null=True, blank=True)
    department = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    start_hour = models.TimeField(auto_now=False, auto_now_add=False)
    end_hour = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    maximum_capacity = models.IntegerField(null=True, blank=True)
    number_of_registered = models.IntegerField(default=0, null=True)
    is_visible = models.BooleanField(default=True)
    direction = models.CharField(max_length=255)
    keynote_speaker = models.CharField(max_length=255)
    connection_link = models.URLField(blank=True, null=True)
    is_registrable = models.BooleanField(default=True)
    social_media = models.URLField(blank=True, null=True)
    image = models.URLField(blank=True, null=True)

    def quota_disponibility(self) -> int:
        """Determina cuantos cupos quedan basado en la capacidad y los registros."""
        if self.maximum_capacity:
            quota = self.maximum_capacity - self.number_of_registered 
            return quota


    def get_availability_ratio(self) -> float:
        """Determina el estado de disponibilidad basado en la capacidad y los registros."""
        if self.maximum_capacity and self.maximum_capacity > 0:            
            ratio = self.number_of_registered / self.maximum_capacity
            return ratio


    def update_number_of_registered(self) -> None:
        """Actualizar el número de participantes registrados"""
        self.number_of_registered = FairRegistration.objects.filter(fair=self).count()
        self.save(update_fields=['number_of_registered'])


    def clean(self):
        # Verificar si la fecha de inicio es mayor que la fecha actual
        if self.start_event_date <= now().date():
            raise ValidationError({'start_event_date': 'La fecha de inicio debe ser mayor a la fecha actual.'})
        
        # Verificar si la fecha de fin (si se proporciona) es posterior a la fecha de inicio
        if self.end_event_date and self.end_event_date < self.start_event_date:
            raise ValidationError({'end_event_date': 'La fecha de fin debe ser posterior a la fecha de inicio.'})
        
        # Verificar que la capacidad maxima sea mayor a 0 (si se proporciona)
        if self.maximum_capacity and self.maximum_capacity <= 0:
            raise ValidationError({'maximum_capacity': 'El aforo debe ser mayor a 0, también puede estar vacío'})

    def save(self, *args, **kwargs):    
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

exploreFairs/views.py
from django.shortcuts import render, get_object_or_404
from .models import JobFair
from .utils import filter_job_fairs
from fairManagement.models import Aspirant
from fairManagement.models import FairRegistration

def view_fairs(request):
    filters = {
        'location': request.GET.get('location'),
        'event_date': request.GET.get('event_date'),
        'organizer': request.GET.get('organizer'),
        'title': request.GET.get('title'),
    }

    # Aplicar los filtros usando la función auxiliar
    fairs = filter_job_fairs(JobFair.objects.all(), filters)
    
    return render(request, 'fairs.html', {'fairs': fairs})

def fair_detail_view(request, id):
    fair = get_object_or_404(JobFair, id=id)
    fair_registration = None

    if request.user.is_authenticated:
        aspirant = Aspirant.objects.get(user=request.user)

    try:
        if FairRegistration.objects.filter(aspirant=aspirant, fair=fair).exists():
            fair_registration = FairRegistration.objects.get(aspirant=aspirant, fair=fair)
    except:
        pass
    
    return render(request, 'detail-fair.html', {'fair': fair, 'fair_registration': fair_registration})

exploreFairs/templates/detail-fair.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/detail-fair.css' %}">
{% endblock links %}

{% block title %}{{ fair.title }} - Ferias de empleo{% endblock title %}

{% block content %}
<div class="event-card-container flex">
  <div class="event-card">
    <div class="event-left">
      <!-- Imagen en la tarjeta -->
      <img src="{{ fair.image }}" alt="Imagen del evento" class="event-image" id="lightbox-image">
    </div>
    <div class="event-right">
      <h2 class="event-title">{{ fair.title }}</h2>
      <p class="event-description">
        {{ fair.description }}
      </p>
      <p class="event-call">¡Inscríbete ahora mismo!</p>
      <div style="display: flex; align-items: center; justify-content: center">
        <form class="fair_button" method="post" action="{% url 'management:favorite_fair' %}">
            {% csrf_token %}
          <input type="hidden" name="fair_id" value="{{ fair.id }}">
          <input type="hidden" name="fair_title" value="{{ fair.title }}">
          <input type="hidden" name="aspirant_id" value="{{ aspirant.id }}">

          <button class="btn-secondary" type="submit">Agregar Feria a Favoritas</button>
        </form>
      </div>
    </div>
    <div class="event-footer">
      <div class="event-info">
        <p><span class="event-label">Organizado por:</span> {{ fair.organizer.email }}</p>
        {% if fair.connection_link %}
          <p><span class="event-label">Link de conexión:</span> <a href="{{ fair.connection_link }}" target="blank">{{ fair.connection_link }}</a></p>
        {% endif %}
        {% if fair.start_event_date == fair.end_event_date %}
          <p><span class="event-label">Fecha: </span>{{ fair.start_event_date|date:"d M Y" }}</p>
        {% else %}
          <p><span class="event-label">Fecha: </span>Desde el {{ fair.start_event_date|date:"d M Y" }} hasta el {{ fair.end_event_date|date:"d M Y" }}</p>
        {% endif %}
        <p><span class="event-label">Hora: </span>{{ fair.start_hour }} - {{ fair.end_hour }}</p>
        <p><span class="event-label">Ciudad:</span> {{fair.city}} - {{ fair.department }}</p>
        <p><span class="event-label">Dirección:</span> {{fair.direction}}</p>
        <p><span class="event-label">Ponente principal:</span> {{ fair.keynote_speaker }}</p>
        {% if fair.social_media %}
          <a href="{{ fair.social_media }}" target="blank" style="display: flex; justify-content: center; margin-top: 10px">
            <image src="{% static 'images/Instagram-icon.svg' %}"/>
          </a>
        {% endif %}
        {% if fair.is_registrable %}
          <p><span class="event-label">Número de personas inscritas:</span> {{ fair.number_of_registered }}</p>
        {% endif %}
      </div>
    </div>
    {% if fair_registration %}
    <form class="event-button" method="get" action="{% url 'successful_inscription' fair_registration.id fair.title %}">
      {% csrf_token %}
      <button class="btn-primary" type="submit">Ver mi QR</button>
    </form>
    {% else %}
      {% if fair.is_registrable %}
        <form class="event-button" method="post" action="{% url 'management:register_fair' fair.id %}">
          {% csrf_token %}
          <input type="hidden" name="fair_id" value="{{ fair.id }}">
          <button class="btn-primary" type="submit">¡Inscribirme!</button>
        </form>
      {% endif %}
    {% endif %}
  </div>
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

exploreFairs/templates/fairs.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/hero-section.css' %}">
<link rel="stylesheet" href="{% static 'css/search.css' %}">
<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock links %}

{% block title %}WorkSpyder - Ferias de empleo{% endblock title %}

{% block content %}
<div class="hero-section">
    <div class="hero-container">
        <div class="header">
            <h1>¿Buscando eventos?</h1>
            <form id="search_bar" method="GET" action="{% url 'view_fairs' %}">
                <input id="search_input" type="search" name="title" placeholder="Encuentralos acá..." value="{{ request.GET.title }}">
                <button type="submit" class="fa fa-search"></button>
            </form>
        </div>
    </div>
    <div class="glassy-overlay"></div>
    <canvas></canvas>
    <script src="{% static 'js/hero-section.js' %}"></script>
</div>
<div class="principal-content-container">
    <section class="main-container" style="justify-content:center; flex-direction: column; align-items: center;">
        <button type="button" class="btn-secondary" onclick="toggleFilters()">Filtros de búsqueda</button> <!-- Botón para colapsar -->
        <div id="filterSection" class="collapsible">
            <form class="filter-form" method="GET" action="{% url 'view_fairs' %}">
                <div class="filter-items-container">
                    <div class="filter-item">
                        <label for="location">Ubicación</label>
                        <input type="text" name="location" placeholder="Ciudad o país" value="{{ request.GET.location }}">
                    </div>
                    <div class="filter-item">
                        <label for="event_date">Fecha</label>
                        <input type="date" name="event_date" value="{{ request.GET.event_date }}">
                    </div>
                    <div class="filter-item">
                        <label for="organizer">Empresa organizadora</label>
                        <input type="text" name="organizer" placeholder="Organizador" value="{{ request.GET.organizer }}">
                    </div>
                </div>
                <button type="submit" class="btn-primary">Aplicar filtros</button>
            </form>
        </div>
    </section>
    <section class="main-container fairs-principal-container flex">
        {% for fair in fairs %}
            <div class="card-fair">
                <div class="img-card-container">
                    <div class="background-gradient"></div>
                    {% if fair.get_availability_ratio >= 1 %}
                        <div class="disponibility">
                            <div style="background-color: #DD2E44;"></div>
                            <h2>Agotado</h2>
                        </div>
                    {% elif fair.get_availability_ratio >= 0.6 %}
                        <div class="disponibility">
                            <div style="background-color: #F4900C;"></div>
                            <h2>Agotandose</h2>
                        </div>
                    {% else %}
                        <div class="disponibility">
                            <div style="background-color: #78B159;"></div>
                            <h2>Disponible</h2>
                        </div>
                    {% endif %}
                    <div class="fair-date">
                        <h2>{{ fair.start_event_date }}</h2>
                    </div>
                    <img src="{{ fair.image }}" alt="{{ fair.title }}">
                </div>
                <div class="data-card-container">
                    <h1>{{ fair.title }}</h1>
                    <p>{{ fair.city }}</p>
                    <button class="btn-primary" onclick="window.location.href='{% url 'fair' fair.id %}'">Ver más info</button>
                </div>
            </div>
        {% empty %}
            <p>No hay ferias disponibles en este momento.</p>
        {% endfor %}
    </section>
</div>
{% endblock content %}

{% block scripts %}
<script>
    function toggleFilters() {
        var filterSection = document.getElementById("filterSection");
        filterSection.classList.toggle("active");
    }
</script>

{% endblock scripts %}