WorkSpyder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exploreFairs.urls')),
    path('management/', include('fairManagement.urls')),
    path('attendance/', include('fairAttendance.urls')),
    path('post/', include('fairsPost.urls')),
    path('auth/', include('auth.urls')),
    path('profile/', include('userProfile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth/urls.py
from django.urls import path
from . import views
#Agregado pata el login
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='view_fairs'), name='logout'),
   ]

fairsPost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import post_home_view, add_fair_view, edit_fair_view, view_published_fairs, view_registered_fair, delete_selected_fair

app_name = 'post'

urlpatterns = [
    path('', post_home_view, name="post_home"),
    path("addfair", add_fair_view, name="add_fair"),
    path("editfair", edit_fair_view, name="edit_fair"),
    path("editfair/<int:feria_id>/", edit_fair_view, name="edit_selected_fair"),
    path("delete-fair/<int:feria_id>/", delete_selected_fair, name="delete_selected_fair"),
    path("my-fairs", view_published_fairs, name="view_published_fairs"),
    path("my-fair/<int:id>/", view_registered_fair, name="view_registered_fair")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userProfile/urls.py
from django.urls import path
from .views import view_profile, edit_profile

app_name = 'profile'

urlpatterns = [
    path('', view_profile, name="view_profile"),
    path('edit', edit_profile, name="edit_profile"),
   ]

WorkSpyder/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Palanquin:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/WorkSpyder-logo.svg' %}" >
    {% block links %}{% endblock links %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <nav class="nav-container flex">
            <a href="{% url "view_fairs" %}">
                <section class="nav-brand flex">
                    <img src="{% static 'images/WorkSpyder-logo.svg' %}" alt="WorkSpyder">
                    <h1>WorkSpyder</h1>
                </section>
            </a>
            <div class="nav-right-elements flex">
                <a class="nav-event nav-btn" href="{% url 'post:post_home' %}">
                    Pon tu evento en WorkSpyder
                </a>
                <button class="nav-user flex nav-btn" onclick="toggleMenu()">
                    <img src="{% static 'images/bars.svg' %}" alt="Menú">
                    {% if user.is_authenticated %}
                        <img class="user-img" src="https://www.gravatar.com/avatar/{{ user.avatar }}?d=retro&f=y&s=128" alt="User Avatar">
                    {% else %}
                        <img class="user-img" src="{% static 'images/user-circle.svg' %}" alt="Usuario">
                    {% endif %}
                </button>
                
                <!-- Menú desplegable -->
                <div id="user-menu" class="user-menu hidden">
                    <ul>
                        {% if user.is_authenticated %}
                        <li><a href="{% url "profile:view_profile" %}">Perfil</a></li>
                        <li><a href="{% url "post:view_published_fairs" %}">Mis ferias</a></li>
                        <li><a>
                            <form method="POST" action="{% url 'auth:logout' %}">
                                {% csrf_token %}
                                <button type="submit">Cerrar sesión</button>
                            </form>
                        </a></li>
                        {% else %}
                        <li><a href="{% url "auth:login" %}">Iniciar Sesión</a></li>
                        <li><a href="{% url "auth:register" %}">Registrarse</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock content %}
    </main>
    <footer>
        <div class="footer-container flex">
            <section class="flex">
                <div class="footer-info-container flex">
                    <span>© 2024 WorkSpyder</span>
                    <span>·</span>
                    <a target="blank" href="https://docs.google.com/forms/d/1t_4JmgtdpoNuSgyvhVgPmEfXNVkeTLii2_c5ckV2WcI/viewform?edit_requested=true">Encuesta de satisfacción</a>
                    <span>·</span>
                    <a target="blank" href="#">Acerca de nosotros</a>
                </div>
                <div class="footer-social-media flex">
                    <a href="https://github.com/JaraCalle/WorkSpyder"><span class="mdi--github"></span></a>
                </div>
            </section>
        </div>
    </footer>
</body>
<script>
    function toggleMenu() {
        const menu = document.getElementById('user-menu');
        if (menu) {
            menu.classList.toggle('show'); // Alterna entre mostrar y ocultar el menú
        } else {
            console.error("El menú no fue encontrado.");
        }
    }
    
    // Cerrar el menú si se hace clic fuera de él
    window.onclick = function(event) {
        const menu = document.getElementById('user-menu');
        if (menu && !menu.contains(event.target) && !event.target.matches('.nav-user, .nav-user *')) {
            menu.classList.remove('show');
        }
    }
</script>
{% block scripts %}{% endblock scripts %}
</html>

WorkSpyder/templates/denied-permission.html
{% extends "base.html" %}
{% block content %}
No cuentas con los permisos necesarios o no eres el creador de esta feria para marcar la asistencia
{% endblock content %}

WorkSpyder/templates/login.html
{% extends 'RegisterLogin/layout.html' %}

{% block content %}

<form class="form" method="post">  
    {% csrf_token %}
    {{ form.as_p}}

    <button type="submit" id="submit">Login</button>
</form>

{% endblock %}

WorkSpyder/templates/logout.html
{% extends 'RegisterLogin/layout.html' %}

{% block content %}

<h1>Te has logeado</h1>

{% endblock %}

WorkSpyder/templates/register.html
{% extends 'RegisterLogin/layout.html' %}

{% block content %}

<form class="form" method="post">  
    {% csrf_token %}
    {{ form.as_p}}

    <button type="submit" id="submit">Registrarse</button>
</form>



{% if messages %}
    {% for message in messages %}
    <div class="notification {{ message.tags}}">
        {{ message }}
    </div>
    {% endfor%}
{% endif %}

{%if request.user.is.authenticated %}
<li> <a href="{% url 'logout' %}">Logout</a> </li>
{% else %}
<li> <a href="{% url 'register' %}">Register</a> </li>
<li> <a href="{% url 'login' %}">Login</a> </li>
{% endif %}



{% endblock %}