WorkSpyder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exploreFairs.urls')),
    path('management/', include('fairManagement.urls')),
    path('attendance/', include('fairAttendance.urls')),
    path('post/', include('fairsPost.urls')),
    path('auth/', include('auth.urls')),
    path('profile/', include('userProfile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth/urls.py
from django.urls import path
from . import views
#Agregado pata el login
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='view_fairs'), name='logout'),
   ]

fairsPost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import post_home_view, add_fair_view, edit_fair_view, view_published_fairs, view_registered_fair, delete_selected_fair

app_name = 'post'

urlpatterns = [
    path('', post_home_view, name="post_home"),
    path("addfair", add_fair_view, name="add_fair"),
    path("editfair", edit_fair_view, name="edit_fair"),
    path("editfair/<int:feria_id>/", edit_fair_view, name="edit_selected_fair"),
    path("delete-fair/<int:feria_id>/", delete_selected_fair, name="delete_selected_fair"),
    path("my-fairs", view_published_fairs, name="view_published_fairs"),
    path("my-fair/<int:id>/", view_registered_fair, name="view_registered_fair")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userProfile/urls.py
from django.urls import path
from .views import view_profile, edit_profile

app_name = 'profile'

urlpatterns = [
    path('', view_profile, name="view_profile"),
    path('edit', edit_profile, name="edit_profile"),
   ]

userProfile/models.py
from django.db import models

# Create your models here.

userProfile/forms.py
from django import forms
from fairManagement.models import Aspirant

class AspirantForm(forms.ModelForm):

    firstName = forms.CharField(
        label="",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Primer nombre'})
    )
    secondName = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Segundo nombre'})
    )
    lastName = forms.CharField(
        label="",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Apellido'})
    )
    phone = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Número de celular', 'type': 'number', 'minlength':"10", 'maxlength':"10"})
    )

    class Meta:
        model = Aspirant
        fields = ['firstName', 'secondName', 'lastName', 'phone']
        help_texts = {k: "" for k in fields}

userProfile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse
from fairManagement.models import Aspirant
from fairManagement.models import FairRegistration
from .forms import AspirantForm

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def view_profile(request):
    aspirant_user = get_object_or_404(Aspirant, user=request.user)
    fairs_registration = FairRegistration.objects.filter(aspirant = aspirant_user)
    return render(request, 'profile.html', {'aspirant': aspirant_user, 'user': request.user, 'fairs_registration': fairs_registration})


@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def edit_profile(request):
    aspirant_user = get_object_or_404(Aspirant, user=request.user)
    
    next_url = request.GET.get('next', reverse('profile:view_profile'))
    fair_id = request.GET.get('fair_id', '')
    
    if request.method == 'GET':
        form = AspirantForm(instance=aspirant_user)
    elif request.method == 'POST':
        form = AspirantForm(request.POST, instance=aspirant_user)
        if form.is_valid():
            form.save()
            return redirect(next_url, fair_id)

    return render(request, 'edit_profile.html', {'form': form})

userProfile/templates/edit_profile.html
{% extends "base.html" %}

{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
	<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
	<link rel="stylesheet" href="{% static 'css/forms.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock links %}

{% block title %}WorkSpyder - Editar perfil{% endblock title %}

{% block content %}
<div class="principal-content-container">
    <section class="main-container form-container" id="create-fair-form">
		<h1>Editando perfil</h1>
		<div>
			<form method="post" enctype="multipart/form-data">
				<div>
					{% csrf_token %}
					{{ form.as_p }}
				</div>
				<button type="submit" class="btn-primary">Guardar cambios</button>
			</form>
		</div>
	</section>
</div>
{% endblock %}

userProfile/templates/profile.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock links %}

{% block title %}{{ aspirant.firstName }} - perfil de Workspyder{% endblock title %}

{% block content %}
<div class="profile-container">
    <section class="user-data-container">
        <img class="user-img" src="https://www.gravatar.com/avatar/{{ user.avatar }}?d=retro&f=y&s=128" alt="User Avatar">
        <h2>{{ aspirant }}</h2>
        <p>{{ aspirant.phone }}</p>
        <button class="btn-secondary" onclick="window.location.href='{% url 'profile:edit_profile' %}'">Editar perfil</button>
    </section>
    <div class="fairs-data-container">
        <h2>Ferias a las que te inscribiste</h2>
        <section class="main-container fairs-principal-container flex">
            {% for fair_registration in fairs_registration %}
                <div class="card-fair" id="card-fair-profile">
                    <div class="img-card-container">
                        <img src="{{ fair_registration.fair.image }}" alt="{{ fair_registration.fair.title }}">
                    </div>
                    <div class="data-card-container">
                        <h1>{{ fair_registration.fair.title }}</h1>
                        <p>{{ fair_registration.fair.event_date|date:"d M Y" }}</p>
                        <button class="btn-primary" onclick="window.location.href='{% url 'fair' fair_registration.fair.id %}'">Ver feria</button>
                        <button class="btn-secondary" onclick="window.location.href='{% url 'successful_inscription' fair_registration.id fair_registration.fair.title %}'">Ver QR</button>
                    </div>
                </div>
            {% empty %}
                <p>No te has inscrito a ninguna feria todavia.</p>
            {% endfor %}
        </section>
        <h3><u><a href="{% url "post:view_published_fairs" %}">¿Buscando tus ferias favoritas?</a></u></h3>
    </div>
</div>
{% endblock %}