WorkSpyder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exploreFairs.urls')),
    path('management/', include('fairManagement.urls')),
    path('attendance/', include('fairAttendance.urls')),
    path('post/', include('fairsPost.urls')),
    path('auth/', include('auth.urls')),
    path('profile/', include('userProfile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth/urls.py
from django.urls import path
from . import views
#Agregado pata el login
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='view_fairs'), name='logout'),
   ]

fairsPost/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import post_home_view, add_fair_view, edit_fair_view, view_published_fairs, view_registered_fair, delete_selected_fair

app_name = 'post'

urlpatterns = [
    path('', post_home_view, name="post_home"),
    path("addfair", add_fair_view, name="add_fair"),
    path("editfair", edit_fair_view, name="edit_fair"),
    path("editfair/<int:feria_id>/", edit_fair_view, name="edit_selected_fair"),
    path("delete-fair/<int:feria_id>/", delete_selected_fair, name="delete_selected_fair"),
    path("my-fairs", view_published_fairs, name="view_published_fairs"),
    path("my-fair/<int:id>/", view_registered_fair, name="view_registered_fair")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fairsPost/models.py
from django.db import models

fairsPost/forms.py
from django import forms
from exploreFairs.models import JobFair 
from .CONST import DEPARTAMENTOS, MUNICIPIOS

class FeriaForm(forms.ModelForm):
    title = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Título del evento'})
    )
    description = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={'class': 'form-input', 'placeholder': 'Descripción del evento', 'rows': 4})
    )
    start_event_date = forms.DateField(
        label="",
        widget=forms.DateInput(attrs={'class': 'form-input', 'type': 'date', 'placeholder': 'Fecha de inicio'})
    )
    end_event_date = forms.DateField(
        label="",
        widget=forms.DateInput(attrs={'class': 'form-input', 'type': 'date', 'placeholder': 'Fecha de finalización'})
    )
    department = forms.ChoiceField(
        choices=DEPARTAMENTOS,
        label="Departamento",
        widget=forms.Select(attrs={'class': 'form-input', 'id': 'usp-custom-departamento-de-residencia'})
    )
    city = forms.ChoiceField(
        choices=MUNICIPIOS,
        label="Municipio",
        widget=forms.Select(attrs={'class': 'form-input', 'id': 'usp-custom-municipio-ciudad'})
    )
    maximum_capacity = forms.IntegerField(
        label="",
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Aforo máximo del evento', 'type': 'number', 'min': '1'})
    )
    is_visible = forms.BooleanField(
        required=False,
        label="¿Hacer visible para todos?",
        widget=forms.CheckboxInput(attrs={'class': 'form-input', 'default': 'check'})
    )
    is_registrable = forms.BooleanField(
        required=False,
        label="Habilitar las inscripciones?",
        widget=forms.CheckboxInput(attrs={'class': 'form-input', 'default': 'check'})
    )
    direction = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Dirección'})
    )
    start_hour = forms.TimeField(
        label="Hora de inicio",
        widget=forms.DateInput(attrs={'class': 'form-input', 'type': 'time', 'placeholder': 'Hora de inicio'})
    )
    end_hour = forms.TimeField(
        label="Hora de cierre",
        required=False,
        widget=forms.DateInput(attrs={'class': 'form-input', 'type': 'time', 'placeholder': 'Hora de cierre'})
    )

    connection_link = forms.CharField(
        label="",
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'Link de conexión virtual (Opcional)'})
    )

    keynote_speaker = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Orador principal'})
    )

    social_media = forms.CharField(
        label="",
        required=False,
        widget=forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'Link de Instagram'})
    )

    class Meta:
        model = JobFair
        fields = [
            'title', 'description', 'start_event_date',
            'end_event_date', 'start_hour', 'end_hour',
            'department', 'city', 'direction',
            'maximum_capacity', 'is_visible', 'is_registrable',
            'keynote_speaker', 'connection_link', 'social_media'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Si deseas mostrar el campo de manera informativa pero no editable
        if 'number_of_registered' in self.fields:
            self.fields['number_of_registered'].disabled = True

fairsPost/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from exploreFairs.models import JobFair
from fairManagement.models import FairRegistration, FairFavorite, Aspirant
from fairAttendance.models import QR
from .CONST import IMGBB_API_URL
from decouple import config
from .forms import FeriaForm
import requests
import os

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def post_home_view(request):
    return render(request, "home.html")

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def add_fair_view(request):
    if request.method == 'POST':
        print(request.FILES)
        form = FeriaForm(request.POST)  # Manejar datos y archivos
        if form.is_valid():
            image_file = request.FILES.get('image')  # Obtener el archivo de la imagen
            
            # Subir el archivo a ImgBB
            try:
                response = requests.post(
                    IMGBB_API_URL,
                    data={'key': config('IMGBB_API_KEY')},
                    files={
                        'image': (image_file.name, image_file.file, image_file.content_type)
                    }
                )
                response_data = response.json()
                
                if response.status_code == 200:
                    # Obtener la URL de la imagen subida
                    img_url = response_data['data']['url']
                    
                    # Guardar la feria en la base de datos
                    fair = form.save(commit=False)  # No guardar todavía
                    fair.organizer = request.user
                    fair.image = img_url  # Asignar la URL
                    fair.save()  # Guardar en la base de datos

                    return redirect('view_fairs')
                else:
                    # Error al subir a ImgBB
                    form.add_error('image', f"Error al subir la imagen: {response_data.get('error', {}).get('message', 'Desconocido')}")
            
            except requests.RequestException as e:
                # Error al realizar la solicitud a ImgBB
                form.add_error('image', f"Error al subir la imagen: {str(e)}")
    else:
        form = FeriaForm()
    
    return render(request, 'addfair.html', {'form': form})

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def edit_fair_view(request, feria_id=None):
    if feria_id:
        feria = get_object_or_404(JobFair, id=feria_id)
        if feria.organizer != request.user:
            return redirect('auth:login')
    else:
        feria = None

    if request.method == 'POST':
        if 'selected_fair' in request.POST:
            feria_id = request.POST.get('selected_fair')
            return redirect('post:edit_selected_fair', feria_id=feria_id)
        form = FeriaForm(request.POST, request.FILES, instance=feria)

        if form.is_valid():
            form.save()
            return redirect('post:edit_fair')
    if feria:
        form = FeriaForm(instance=feria)
    else:
        form = None

    ferias = JobFair.objects.filter(organizer=request.user)
    return render(request, 'editfair.html', {'form': form, 'ferias': ferias, 'selected_feria': feria})

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def view_published_fairs(request):
    ferias = JobFair.objects.filter(organizer=request.user)
    aspirant = get_object_or_404(Aspirant, user=request.user)
    favorites = FairFavorite.objects.filter(aspirant=aspirant)
    fairs_registration = FairRegistration.objects.filter(aspirant = aspirant)
    return render(request, "published_fairs.html", {'ferias': ferias, 'favorites': favorites, 'fairs_registration': fairs_registration})

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def view_registered_fair(request, id):
    fair = get_object_or_404(JobFair, id=id)
    qrs = QR.objects.filter(registration__fair=fair)
    return render(request, 'registered_fair.html', {'fair': fair, 'registers': qrs})

@user_passes_test(lambda u: u.is_authenticated, login_url='auth:login')
def delete_selected_fair(request, feria_id):
    feria = get_object_or_404(JobFair, id=feria_id)
    if feria.organizer != request.user:
        return redirect('exploreFairs:view_fairs')
    
    feria.delete()
    return redirect('post:view_published_fairs')

fairsPost/templates/addfair.html
{% extends "base.html" %}

{% load static %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
	<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
	<link rel="stylesheet" href="{% static 'css/forms.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script type="text/javascript" src="{% static "js/populate/colombia.js" %}"></script>
{% endblock links %}

{% block title %}WorkSpyder - Crear Nueva Feria{% endblock title %}

{% block content %}
<div class="principal-content-container">
    <section class="main-container form-container" id="create-fair-form">
		<h1>Crear una feria nueva</h1>
		<div>
			<form method="post" enctype="multipart/form-data">
				<div>
					{% csrf_token %}
					{{ form.as_p }}
					<p>	
						<label>Imagen de la feria:</label>
						<input type="file" name="image" class="form-input" accept="image/*">
					</p>
				</div>
				<button type="submit" class="btn-primary">Agregar Feria</button>
			</form>
		</div>
	</section>
</div>
{% endblock content %}

fairsPost/templates/editfair.html
{% extends "base.html" %}

{% load static %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
	<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
	<link rel="stylesheet" href="{% static 'css/forms.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script type="text/javascript" src="{% static "js/populate/colombia.js" %}"></script>
{% endblock links %}

{% block title %}WorkSpyder - Editar Feria{% endblock title %}

{% block content %}
<div class="principal-content-container">
	<form method="post">
		{% csrf_token %}
		<section class="main-container fairs-principal-container flex">
			{% for feria in ferias %}
			<div>
				<div class="card-fair">
					<div class="img-card-container">
						<img src="{{ feria.image }}" alt="{{ fair.title }}">
					</div>
					<div class="data-card-container">
						<h1>{{ feria.title }}</h1>
						<p>{{ feria.organizer }}</p>
					</div>
					<div class="radio-input-container">
						<input class="option-input radio" type="radio" name="selected_fair" value="{{ feria.id }}" {% if feria == selected_feria %}checked{% endif %} required>
					</div>
				</div>
			</div>
			{% endfor %}
			<button type="submit" class="btn-secondary">Seleccionar Feria</button>
		</section>
	</form>
	{% if form %}
	<section class="main-container form-container" id="edit-fair-form">
		<h1>Editar una feria</h1>
		<div>
			<form method="post" enctype="multipart/form-data">
				<div>
					{% csrf_token %}
					{{ form.as_p }}
				</div>
				<!-- Contenedor para la previsualización de la imagen -->
				<div id="image-preview-container" style="margin-top: 15px; display:flex; justify-content:center;">
					<img 
						id="image-preview" 
						src="{{ form.instance.image }}" 
						alt="Previsualización de la imagen" 
						style="display: {{ form.instance.image }}; max-width: 100%; height: auto; border-radius: 15px; padding: 5px;"
					>
				</div>
				<button type="submit" class="btn-primary">¡Publicar!</button>
			</form>
		</div>
	</section>
	{% endif %}
</div>
{% endblock content %}

{% block script %}
	<script>
		document.addEventListener('DOMContentLoaded', function () {
			const imageInput = document.querySelector('input[type="file"]');
			const imagePreview = document.getElementById('image-preview');

			imageInput.addEventListener('change', function () {
				const file = imageInput.files[0];
				if (file) {
					const reader = new FileReader();
					reader.onload = function (e) {
						imagePreview.src = e.target.result;
						imagePreview.style.display = 'block';
					};
					reader.readAsDataURL(file);
				} else {
					imagePreview.style.display = 'none';
				}
			});
		});
	</script>
{% endblock script %}

fairsPost/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock links %}

{% block title %}WorkSpyder - Manejador de Ferias{% endblock title %}

{% block content %}
<div class="principal-content-container" style="height: 80vh;">
  <section class="main-container fairs-manager-container">
    <h1>Bienvenido al manejador de ferias de WorkSpyder</h1>
    <h4>Selecciona que deseas realizar</h4>
    <div class="optionSelect">
      <ul>
        <li><a href="{% url 'post:add_fair' %}" target="_self"><button class="btn-primary">Publicar una feria</button></a></li>
        <li><a href="{% url 'post:edit_fair' %}" target="_self"><button class="btn-secondary">Editar una feria existente</button></a></li>
      </ul>
    </div>
  </section>
</div>
{% endblock content %}

fairsPost/templates/published_fairs.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock links %}

{% block title %}WorkSpyder - Mis ferias{% endblock title %}

{% block content %}
<div class="principal-content-container" id="my-fairs-container">
    {% if ferias %}
        <section class="main-container fairs-manager-container" id="my_fairs">
            <h1>Tus ferias publicadas</h1>
            <div class="optionSelect">
                <ul class="fairs-list">
                    {% for fair in ferias %}
                    <li>
                        <div class="single-fair">
                            <img src="{{ fair.image }}" alt="Imagen del evento">
                            <div>
                                <h2>{{ fair.title }}</h2>
                                <p>{{fair.city}} - {{ fair.department }}</p>
                            </div>
                            <div style="display: flex; flex-direction: column;">
                                <button class="btn-secondary" onclick="window.location.href='{% url 'post:view_registered_fair' fair.id %}'">Ver inscritos</button>
                                <button class="btn-primary" onclick="window.location.href='{% url 'post:edit_selected_fair' fair.id %}'">Editar</button>
                                <button class="btn-danger" onclick="window.location.href='{% url 'post:delete_selected_fair' fair.id %}'">Eliminar</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    {% else %}
    <section class="main-container fairs-manager-container">
        <p>No has publicado ningún evento o feria todavia.</p>
    </section>
    {% endif %}
    {% if favorites %}
        <section class="main-container fairs-manager-container" id="favorite_fairs">
            <h1>Mis Ferias Favoritas</h1>
            <div class="optionSelect">
                <ul class="fairs-list">
                    {% for favorite in favorites %}
                    <li>
                        <div class="single-fair">
                            <img src="{{ favorite.fair.image }}" alt="Imagen del evento">
                            <div>
                                <h2>{{ favorite.fair.title }}</h2>
                                <p>{{favorite.fair.city}} - {{ favorite.fair.department }}</p>
                            </div>
                            <div>
                                <button class="btn-primary" onclick="window.location.href='{% url 'fair' favorite.fair.id %}'">Ver Feria</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
    {% endif %}
    {% if fairs_registration %}
        <section class="main-container fairs-manager-container">
            <h1>Ferias a las que te has inscrito</h1>
            <div class="optionSelect">
                <ul class="fairs-list">
                    {% for fair_register in fairs_registration %}
                    <li>
                        <div class="single-fair">
                            <img src="{{ fair_register.fair.image }}" alt="Imagen del evento">
                            <div>
                                <h2>{{ fair_register.fair.title }}</h2>
                                <p>{{fair_register.fair.city}} - {{ fair_register.fair.department }}</p>
                            </div>
                            <div>
                                <button class="btn-secondary" onclick="window.location.href='{% url 'successful_inscription' fair_register.id fair_register.fair.title %}'">Ver QR</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
        {% else %}
        <section class="main-container fairs-manager-container">
            <p>No te has inscrito a ninguna feria todavia.</p>
        </section>
    {% endif %}
</div>
{% endblock %}

fairsPost/templates/registered_fair.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/principal-content.css' %}">
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/fairs-manager.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock links %}

{% block title %}WorkSpyder - Inscritos a {{ fair.title }}{% endblock title %}

{% block content %}
<div class="principal-content-container" style="height: 80vh;">
  <section class="main-container fairs-manager-container" id="my_fairs">
    <h1>{{ fair.title }}</h1>
    <table>
      <thead>
        <tr>
          <th>Aspirante</th>
          <th>Asistencia Marcada</th>
        </tr>
      </thead>
      <tbody>
        {% for registered in registers %}
          <tr>
            <td>{{ registered.registration.aspirant }}</td>
            <td>{{ registered.isRead|yesno:"✅,⛔" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
  </div>
{% endblock %}